In [16]:
from jpx.jpxconfig import jpxdb_path, tmp_dir
from jpx.crawler import *
from sqlite_pandas.models import sqlite_pandas as sp

import pandas as pd
from datetime import datetime
import glob
jpxdb = sp(jpxdb_path)

def dump_codelist():
    file = glob.glob(tmp_dir + '*.xls')[0]
    df = pd.read_excel(file)
    
    col = {
        'date':None,
        'code':'unique',
        'name':'unique',
        'market':None,
        'gyosyu_kubun33_code':None,
        'gyosyu_kubun33':None,
        'gyosyu_kubun17_code':None,
        'gyosyu_kubun17':None,
        'scale_code':None,
        'scale_kubun':None,
    }
    jpxdb.drop_table('code_list')
    jpxdb.create_table('code_list', col)
    jpxdb.insert_data('code_list', df)
    print('jpx code list excel is dumped to code list table in jpx_db')

In [17]:
dump_codelist()

jpx code list excel is dumped to code list table in jpx_db

In [19]:
jpxdb.get_dataframe('code_list').head()

,date,code,name,market,gyosyu_kubun33_code,gyosyu_kubun33,gyosyu_kubun17_code,gyosyu_kubun17,scale_code,scale_kubun
0,20200930,1301,極洋,市場第一部（内国株）,50,水産・農林業,1,食品,7,TOPIX Small 2
1,20200930,1305,ダイワ上場投信－トピックス,ETF・ETN,-,-,-,-,-,-
2,20200930,1306,ＮＥＸＴ ＦＵＮＤＳ ＴＯＰＩＸ連動型上場投信,ETF・ETN,-,-,-,-,-,-
3,20200930,1308,上場インデックスファンドＴＯＰＩＸ,ETF・ETN,-,-,-,-,-,-
4,20200930,1309,ＮＥＸＴ ＦＵＮＤＳ ＣｈｉｎａＡＭＣ・中国株式・上証５０連動型上場投信,ETF・ETN,-,-,-,-,-,-